port: '8000'

debug: false

db:
  host: 'localhost'
  port: '5436'
  dbname: 'postgres'
  sslmode: 'disable'

rdb:
  host: 'localhost'
  port: '6379'
  dbname: '0'
  password: ''

nats:
  url: 'nats://localhost:4222'

tracer:
  url: 'http://localhost:14268/api/traces'